### ISSUE TITLE
Trait 'BrianFaust\Addressable\HasAddresses' not found

### ISSUE THREAD

**Issue by juanjodomenech** [artisanry/addressable#18]
Hello, 

in the documentation there is a bug in the Set up Model section.

If we use  "use BrianFaust\Addressable\HasAddresses;"  we get "Trait 'BrianFaust\Addressable\HasAddresses' not found". 

The correct is "use BrianFaust\Addressable\Traits\HasAddresses;"

Regards

**Comment by faustbrian** [comment]
https://github.com/artisanry/addressable/commit/77a55b39d2619e6255a83ea6b47289062e0fddcb
